In [1]:
!pip install numpy

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
      --------------------------------------- 0.2/14.8 MB 5.8 MB/s eta 0:00:03
     - -------------------------------------- 0.7/14.8 MB 8.6 MB/s eta 0:00:02
     ---- ----------------------------------- 1.6/14.8 MB 13.0 MB/s eta 0:00:02
     ------ --------------------------------- 2.5/14.8 MB 13.3 MB/s eta 0:00:01
     --------- ------------------------------ 3.4/14.8 MB 15.7 MB/s eta 0:00:01
     ----------- ---------------------------- 4.4/14.8 MB 16.3 MB/s eta 0:00:01
     ------------- -------------------------- 5.1/14.8 MB 16.3 MB/s eta 0:00:01
     -------------- ------------------------- 5.4/14.8 MB 15.0 MB/s eta 0:00:01
     ------------------ --------------------- 6.7/14.8 MB 16.6 MB/s eta 0:00:01
     -------------------- ------------------- 7.7/14.8 MB 16.9 MB/s eta 0:00:01
     ----------------------- ---------------- 8.6/14.8 MB 17.3 MB/s eta 0:00:01
     ------------------------- -------------- 9.5/

In [4]:
import numpy as np

my_list = [1,2,3,4,5,6]
arr = np.array(my_list)

print(type(arr), type(my_list))
print(arr)
print(arr.shape)

<class 'numpy.ndarray'> <class 'list'>
[1 2 3 4 5 6]
(6,)


In [10]:
arr2 = np.array([[1,2,3,0],[4,5,6,0],[7,8,9,0]])
print(arr2)
print(arr2.shape)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
(3, 4)


In [11]:
# To convert the dimensions -> .reshape
arr2.reshape(4,3)

array([[1, 2, 3],
       [0, 4, 5],
       [6, 0, 7],
       [8, 9, 0]])

In [12]:
arr2.reshape(2,6)

array([[1, 2, 3, 0, 4, 5],
       [6, 0, 7, 8, 9, 0]])

In [15]:
arr2

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [13]:
arr2[0]

array([1, 2, 3, 0])

In [14]:
# array_name[from_row:to_row(excluded), from_column:to_column(excluded)]
arr2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [16]:
arr2[0:3,3:4]

array([[0],
       [0],
       [0]])

In [18]:
# np.arrange(from,to,step(gap))
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [19]:
# np.linspace(1-from,10-to,50-num of points)
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])